spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
        dialect: ${JPA_DIALECT}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    lettuce:
      pool:
        max-active: ${REDIS_MAX_ACTIVE}
        max-idle: ${REDIS_MAX_IDLE}
        min-idle: ${REDIS_MIN_IDLE}
  jwt:
    secret: ${JWT_SECRET}
    token:
      access:
        expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
      refresh:
        expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL}
    org.hibernate.type.descriptor.sql: ${LOGGING_LEVEL_HIBERNATE_TYPE}

# 아마존 연결
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: ${AWS_STACK_AUTO}
    s3:
      bucket: ${AWS_S3_BUCKET}
      dir: ${AWS_S3_DIR}

# 이메일 설정
gmail:
  host: ${GMAIL_HOST}
  port: ${GMAIL_PORT}
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_PASSWORD}

naver:
  host: ${NAVER_HOST}
  port: ${NAVER_PORT}
  username: ${NAVER_USERNAME}
  password: ${NAVER_PASSWORD}

# USER ID 공개키, 비밀키 세팅
user:
  id-encryption:
    public-key: ${USER_ID_ENCRYPTION_PUBLIC_KEY}
    private-key: ${USER_ID_ENCRYPTION_PRIVATE_KEY}


util:
  secret-key: ${UTIL_SECRET_KEY}